sudo: required
language: java
jdk:
- openjdk8
before_script:
- wget http://services.gradle.org/distributions/gradle-5.6.2-bin.zip
- unzip gradle-5.6.2-bin.zip
- export GRADLE_HOME=$PWD/gradle-5.6.2
- export PATH=$GRADLE_HOME/bin:$PATH
addons:
  sonarcloud:
    organization: awt-04
    token:
      secure: "$SONAR_TOKEN"
script:
- gradle compileJava compileTestJava
- sonar-scanner
- gradle runFeatures
notifications:
  email: true
before_install:
- openssl aes-256-cbc -K $encrypted_d40277219749_key -iv $encrypted_d40277219749_iv
  -in configJson/config.json.enc -out configJson/config.json -d
