sudo: required
language: java
jdk:
- openjdk8
before_script:
- wget http://services.gradle.org/distributions/gradle-5.6.2-bin.zip
- unzip gradle-5.6.2-bin.zip
- export GRADLE_HOME=$PWD/gradle-5.6.2
- export PATH=$GRADLE_HOME/bin:$PATH
addons:
  chrome: stable
  sonarcloud:
    organization: awt-04
    token:
      secure: "$SONAR_TOKEN"
script:
- gradle compileJava compileTestJava
- sonar-scanner
- gradle check
- gradle executeFeatures
notifications:
  email: true
before_install:
- openssl aes-256-cbc -K $encrypted_4bfe49639030_key -iv $encrypted_4bfe49639030_iv
  -in configJson/config.json.enc -out configJson/config.json -d
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
